In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
import numpy as np

In [10]:
senetnces = [ "I ate my apple yeasterday.",
             "That day what were you doing under shades.",
             "I am a good developer.",
             "The cup of tea.",
             "Prime minister is appointed for third time in a row.",
             "If you like this, give it a star."
]

In [11]:
senetnces

['I ate my apple yeasterday.',
 'That day what were you doing under shades.',
 'I am a good developer.',
 'The cup of tea.',
 'Prime minister is appointed for third time in a row.',
 'If you like this, give it a star.']

In [12]:
vocab_size = 10000

In [13]:
one_hot?

Signature:
one_hot(
    input_text,
    n,
    filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
    lower=True,
    split=' ',
    analyzer=None,
)
Docstring: DEPRECATED.
File:      c:\users\shory\anaconda3\envs\myenv\lib\site-packages\keras\src\legacy\preprocessing\text.py
Type:      function

In [14]:
one_hot_vector = [one_hot(word, vocab_size) for word in senetnces]
one_hot_vector

[[2684, 4133, 4633, 5476, 5473],
 [3753, 8231, 2237, 3385, 825, 29, 8648, 5648],
 [2684, 3006, 5797, 2742, 4014],
 [391, 506, 9958, 4265],
 [9150, 7302, 1141, 6189, 4574, 9161, 8524, 3777, 5797, 3106],
 [1241, 825, 1151, 923, 8286, 7583, 5797, 1274]]

In [15]:
max_sentence_length = 10

padded_one_hot_rep = pad_sequences(one_hot_vector, padding = 'pre', maxlen = max_sentence_length)


In [16]:
padded_one_hot_rep

array([[   0,    0,    0,    0,    0, 2684, 4133, 4633, 5476, 5473],
       [   0,    0, 3753, 8231, 2237, 3385,  825,   29, 8648, 5648],
       [   0,    0,    0,    0,    0, 2684, 3006, 5797, 2742, 4014],
       [   0,    0,    0,    0,    0,    0,  391,  506, 9958, 4265],
       [9150, 7302, 1141, 6189, 4574, 9161, 8524, 3777, 5797, 3106],
       [   0,    0, 1241,  825, 1151,  923, 8286, 7583, 5797, 1274]])

In [17]:
from keras import layers, models

input_layer = layers.Input(shape = (max_sentence_length,), name = 'input_layer')
output_layer = layers.Embedding(vocab_size, output_dim = 10, name = 'output_layer')(input_layer)

model = models.Model(input_layer, output_layer, name = 'word_embedding_model')

model.summary()

Model: "word_embedding_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Embedding)        │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(optimizer = 'adam', loss = 'mse')

In [19]:
model.predict(padded_one_hot_rep)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step


array([[[-2.88466942e-02,  5.06304204e-04, -4.26993035e-02,
         -7.04703480e-03,  4.57493551e-02,  2.79680155e-02,
         -2.13937517e-02,  4.37801518e-02,  2.72182338e-02,
         -1.69398077e-02],
        [-2.88466942e-02,  5.06304204e-04, -4.26993035e-02,
         -7.04703480e-03,  4.57493551e-02,  2.79680155e-02,
         -2.13937517e-02,  4.37801518e-02,  2.72182338e-02,
         -1.69398077e-02],
        [-2.88466942e-02,  5.06304204e-04, -4.26993035e-02,
         -7.04703480e-03,  4.57493551e-02,  2.79680155e-02,
         -2.13937517e-02,  4.37801518e-02,  2.72182338e-02,
         -1.69398077e-02],
        [-2.88466942e-02,  5.06304204e-04, -4.26993035e-02,
         -7.04703480e-03,  4.57493551e-02,  2.79680155e-02,
         -2.13937517e-02,  4.37801518e-02,  2.72182338e-02,
         -1.69398077e-02],
        [-2.88466942e-02,  5.06304204e-04, -4.26993035e-02,
         -7.04703480e-03,  4.57493551e-02,  2.79680155e-02,
         -2.13937517e-02,  4.37801518e-02,  2.721823

In [20]:
model.predict(padded_one_hot_rep)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([[-0.02884669,  0.0005063 , -0.0426993 , -0.00704703,  0.04574936,
         0.02796802, -0.02139375,  0.04378015,  0.02721823, -0.01693981],
       [-0.02884669,  0.0005063 , -0.0426993 , -0.00704703,  0.04574936,
         0.02796802, -0.02139375,  0.04378015,  0.02721823, -0.01693981],
       [-0.02884669,  0.0005063 , -0.0426993 , -0.00704703,  0.04574936,
         0.02796802, -0.02139375,  0.04378015,  0.02721823, -0.01693981],
       [-0.02884669,  0.0005063 , -0.0426993 , -0.00704703,  0.04574936,
         0.02796802, -0.02139375,  0.04378015,  0.02721823, -0.01693981],
       [-0.02884669,  0.0005063 , -0.0426993 , -0.00704703,  0.04574936,
         0.02796802, -0.02139375,  0.04378015,  0.02721823, -0.01693981],
       [-0.00311351,  0.01261434,  0.04606236, -0.02730666,  0.04654229,
        -0.01907125,  0.01879791,  0.01223274,  0.02136261, -0.00833373],
       [ 0.04708474,  0.01665609, -0.00461344, -0.03132214, -0.02887993,
        -0.01092168, -0.02858151,  0.00785619